#pragma once

namespace py::err {
    void bad_internal_call();
}
